name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

env:
  NODE_ENV: test
  DATABASE_URL: postgres://postgres:password@localhost:5432/approved-premises-test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret
  OPENSEARCH_URL: http://localhost:9200/
  OPENSEARCH_INDEX_NAME: bed_availability_test
  DATABASE_SEED_FILE: ./data/ap_beds.csv
  GEOLOCATION_SEED_FILE: ./data/ap_geolocations.csv

jobs:
  test:
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: approved-premises-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Load seed data
        env:
          APBEDS_DATA: ${{ secrets.APBEDS_DATA }}
          APGEOLOCATION_DATA: ${{ secrets.APGEOLOCATION_DATA }}
        run: |
          mkdir -p data
          echo $APBEDS_DATA | base64 -d | gzip -d > data/ap_beds.csv
          echo $APGEOLOCATION_DATA | base64 -d | gzip -d > data/ap_geolocations.csv

      - name: Installing dependencies
        run: npm install

      - name: Building source
        run: npm run build

      - name: Run tests
        id: test
        run: script/test
